# Generated by Django 4.2.5 on 2023-09-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_usermodel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel2',
        ),
    ]
